src: "src"
target: "target"
layout: "_layout.{{ext}}"

before: "echo before hook"
after: "echo after hook"

includes: ["_feature.html"] # filename, glob
excludes: ["glob:**/*.exe"] # filename, glob

render_exts: ["md", "html"] # extensions
render_excludes: ["EXAMPLE.md"] # filename, glob

fingerprint_exts: ["jpg", "jpeg", "png", "gif"] # extensions
fingerprint_excludes: ["favicon.jpg"] # filename, glob

bundles:
  - src: ["glob:css/*.css"]
    target: "all.css"
    minify: true
    fingerprint: true
  - src: ["glob:js/*.js"]
    target: "all.js"
    minify: true
    fingerprint: true
