src: "src"
target: "target"
layout: "_layout.{{ext}}"
database: "db.yml"
url: "https://example.com"
trailing_slash: false

before: "echo before hook"
after: "echo after hook"

includes: ["_feature.html"] # filename, glob
excludes: ["glob:**/*.exe"] # filename, glob

render_exts: ["md", "html"] # extensions
render_excludes: ["EXAMPLE.md"] # filename, glob

fingerprint_exts: ["jpg", "jpeg", "png", "gif"] # extensions
fingerprint_excludes: ["favicon.jpg"] # filename, glob

bundles:
  - src: ["glob:css/*.css"]
    target: "all.css"
    minify: true
    fingerprint: true
  - src: ["glob:js/*.js"]
    target: "all.js"
    minify: true
    fingerprint: true

lists:
  - id: "blog"
    src: ["glob:blog/*"]
    target: "."
    prefix: "date" # nil, "date", or "position"
    prefix_include: false
    reverse: true # sort by newest first
    rss:
      title: "Blog"
      description: "Lorem Ipsum"
      limit: 20 # defaults to unlimited
      target: "rss.xml" # defaults to "rss.xml"
  - id: "tips"
    src: ["glob:tips/*"]
    target: "."
    prefix: "position"
    prefix_include: true
